//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WinDeKikaigoV2.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_ASMINPUTBARDLG              101
#define IDD_DIALOGBAR_L                 103
#define IDD_DIALOGBAR_R                 104
#define IDD_EMU6502OUTPUTV2_FORM        107
#define IDR_EMU6502OUTPUTV2_TMPL        108
#define IDR_MAINFRAME                   128
#define IDR_WINDEKTYPE                  129
#define IDD_DIALOG1                     130
#define IDB_OP_LDA                      135
#define IDB_OP_LDX                      136
#define IDB_OP_LDY                      137
#define IDB_OP_STA                      138
#define IDB_OP_STX                      139
#define IDB_OP_STY                      140
#define IDB_OP_TAX                      141
#define IDB_OP_TXA                      142
#define IDB_OP_TAY                      143
#define IDB_OP_TYA                      144
#define IDB_OP_TSX                      145
#define IDB_OP_TXS                      146
#define IDB_OP_PHA                      147
#define IDB_OP_NOP                      153
#define IDB_OP_CLV                      154
#define IDB_OP_CLC                      155
#define IDB_OP_SEC                      156
#define IDB_OP_CLD                      157
#define IDB_OP_SED                      158
#define IDB_OP_CLI                      159
#define IDB_OP_SEI                      160
#define IDB_OP_BVC                      161
#define IDB_OP_BVS                      162
#define IDB_OP_BCC                      163
#define IDB_OP_BCS                      164
#define IDB_OP_BPL                      165
#define IDB_OP_BMI                      166
#define IDB_OP_BNE                      167
#define IDB_OP_BEQ                      168
#define IDB_OP_BIT                      169
#define IDB_OP_CPY                      170
#define IDB_OP_CPX                      171
#define IDB_OP_CMP                      172
#define IDB_OP_RTI                      173
#define IDB_OP_BRK                      174
#define IDB_OP_RTS                      175
#define IDB_OP_JSR                      176
#define IDB_OP_JMP                      177
#define IDB_OP_DEY                      178
#define IDB_OP_DEC                      179
#define IDB_OP_DEX                      180
#define IDB_OP_INY                      181
#define IDB_OP_INX                      182
#define IDB_OP_INC                      183
#define IDB_OP_ROL                      184
#define IDB_OP_ROR                      185
#define IDB_OP_LSR                      186
#define IDB_OP_ASL                      187
#define IDB_OP_SBC                      188
#define IDB_OP_ADC                      189
#define IDB_OP_EOR                      190
#define IDB_OP_ORA                      191
#define IDB_OP_AND                      192
#define IDB_OP_PLP                      193
#define IDB_OP_PHP                      194
#define IDB_OP_PLA                      195
#define IDC_TEST_LABEL                  1021
#define IDC_TEST_LABEL2                 1022
#define IDC_EDIT_PC                     1031
#define IDC_EDIT_REGA                   1032
#define IDC_EDIT_REGX                   1033
#define IDC_EDIT_REGY                   1034
#define IDC_EDIT_REGS                   1035
#define IDC_EDIT_STACK                  1036
#define IDC_CHECK_FLAG_N                1037
#define IDC_CHECK_FLAG_V                1038
#define IDC_CHECK_FLAG_R                1039
#define IDC_CHECK_FLAG_B                1040
#define IDC_CHECK_FLAG_D                1041
#define IDC_CHECK_FLAG_I                1042
#define IDC_CHECK_FLAG_Z                1043
#define IDC_CHECK_FLAG_C                1044
#define IDC_PANE_LDA                    5000
#define IDC_PANE_LDX                    5001
#define IDC_PANE_LDY                    5002
#define IDC_PANE_STA                    5003
#define IDC_PANE_STX                    5004
#define IDC_PANE_STY                    5005
#define IDC_PANE_TXA                    5006
#define IDC_PANE_TYA                    5007
#define IDC_PANE_TXS                    5008
#define IDC_PANE_TAX                    5009
#define IDC_PANE_TAY                    5010
#define IDC_PANE_TSX                    5011
#define IDC_PANE_PHA                    5012
#define IDC_PANE_PHP                    5013
#define IDC_PANE_PLA                    5014
#define IDC_PANE_PLP                    5015
#define IDC_PANE_AND                    5016
#define IDC_PANE_ORA                    5017
#define IDC_PANE_EOR                    5018
#define IDC_PANE_ADC                    5019
#define IDC_PANE_SBC                    5020
#define IDC_PANE_ASL                    5021
#define IDC_PANE_LSR                    5022
#define IDC_PANE_ROL                    5023
#define IDC_PANE_ROR                    5024
#define IDC_PANE_INC                    5025
#define IDC_PANE_INX                    5026
#define IDC_PANE_INY                    5027
#define IDC_PANE_DEC                    5028
#define IDC_PANE_DEX                    5029
#define IDC_PANE_DEY                    5030
#define IDC_PANE_CMP                    5031
#define IDC_PANE_CPX                    5032
#define IDC_PANE_CPY                    5033
#define IDC_PANE_BIT                    5034
#define IDC_PANE_JMP                    5035
#define IDC_PANE_JSR                    5036
#define IDC_PANE_RTS                    5037
#define IDC_PANE_BRK                    5038
#define IDC_PANE_RTI                    5039
#define IDC_PANE_BEQ                    5040
#define IDC_PANE_BNE                    5041
#define IDC_PANE_BMI                    5042
#define IDC_PANE_BPL                    5043
#define IDC_PANE_BCS                    5044
#define IDC_PANE_BCC                    5045
#define IDC_PANE_BVS                    5046
#define IDC_PANE_BVC                    5047
#define IDC_PANE_CLI                    5048
#define IDC_PANE_CLD                    5049
#define IDC_PANE_CLC                    5050
#define IDC_PANE_CLV                    5051
#define IDC_PANE_SEI                    5052
#define IDC_PANE_SED                    5053
#define IDC_PANE_SEC                    5054
#define IDC_PANE_NOP                    5055
#define IDC_ASMDLG_0                    5100
#define IDC_ASMDLG_1                    5101
#define IDC_ASMDLG_2                    5102
#define IDC_ASMDLG_3                    5103
#define IDC_ASMDLG_4                    5104
#define IDC_ASMDLG_5                    5105
#define IDC_ASMDLG_6                    5106
#define IDC_ASMDLG_7                    5107
#define IDC_ASMDLG_8                    5108
#define ID_APP_RIGHTPANE                32771
#define ID_APP_LEFTPANE                 32772
#define ID_APP_DEBUG                    32773
#define ID_APP_RESET                    32774
#define ID_APP_VM                       32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        196
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1038
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
